name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache protobuf library
      id: cache-protobuf
      uses: actions/cache@v1
      with:
        path: protobuf
        key: ${{ runner.os }}-protobuf
    - name: Build protobuf library
      if: steps.cache-protobuf.outputs.cache-hit != 'true'
      run: |
         git clone https://github.com/protocolbuffers/protobuf.git
         cd protobuf
         git submodule update --init --recursive
         ./autogen.sh
         ./autogen.sh
         ./configure
         make
         make check
    - name: Install protobuf library
      run: |
         cd protobuf
         sudo make install
         sudo ldconfig
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
